config/routes.rb
Rails.application.routes.draw do
  resources :winners

  resources :tickets
  resources :shasums

  root 'tickets#new'

end

app/models/shasum.rb
class Shasum < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  validates_uniqueness_of :username, case_sensitive: false

  def validate
    if $deadline < Time.now
      return false
    else
      client = Snooby::Client.new
      response = client.user(self.username).about['created']
      if response > 1416365304
        return false
      else
        return true
      end
    end
  end
end

app/models/winner.rb
class Winner < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shasums_controller.rb
class ShasumsController < ApplicationController
  before_action :set_shasum, only: [:show, :edit, :update, :destroy]

  # GET /shasums
  # GET /shasums.json
  def index
    @shasums = Shasum.all
  end

  # GET /shasums/1
  # GET /shasums/1.json
  def show
  end

=begin
  # GET /shasums/new
  def new
    @shasum = Shasum.new
  end

  # GET /shasums/1/edit
  def edit
  end

  # POST /shasums
  # POST /shasums.json
  def create
    @shasum = Shasum.new(shasum_params)

    respond_to do |format|
      if @shasum.save
        format.html { redirect_to @shasum, notice: 'Shasum was successfully created.' }
        format.json { render :show, status: :created, location: @shasum }
      else
        format.html { render :new }
        format.json { render json: @shasum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shasums/1
  # PATCH/PUT /shasums/1.json
  def update
    respond_to do |format|
      if @shasum.update(shasum_params)
        format.html { redirect_to @shasum, notice: 'Shasum was successfully updated.' }
        format.json { render :show, status: :ok, location: @shasum }
      else
        format.html { render :edit }
        format.json { render json: @shasum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shasums/1
  # DELETE /shasums/1.json
  def destroy
    @shasum.destroy
    respond_to do |format|
      format.html { redirect_to shasums_url, notice: 'Shasum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shasum
      @shasum = Shasum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shasum_params
      params.require(:shasum).permit(:sum)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    
    respond_to do |format|
      if @ticket.save
        if !@ticket.validate
          @ticket.destroy
          format.html { redirect_to tickets_url, notice: 'Unable to create entry.' }
        else
          format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
          format.json { render :show, status: :created, location: @ticket }
        end
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:username)
    end
end

app/controllers/winners_controller.rb
class WinnersController < ApplicationController

  # GET /winners
  # GET /winners.json
  def index
    @winners = Winner.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def winner_params
      params.require(:winner).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shasums_helper.rb
module ShasumsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/winners_helper.rb
module WinnersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainmaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shasums/_form.html.erb
<%= form_for(@shasum) do |f| %>
  <% if @shasum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shasum.errors.count, "error") %> prohibited this shasum from being saved:</h2>

      <ul>
      <% @shasum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sum %><br>
    <%= f.text_field :sum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shasums/edit.html.erb
<h1>Editing shasum</h1>

<%= render 'form' %>

<%= link_to 'Show', @shasum %> |
<%= link_to 'Back', shasums_path %>

app/views/shasums/index.html.erb
<h1>Listing shasums</h1>

<table>
  <thead>
    <tr>
      <th>Sum</th>
      <th></th>
      <th>Created At</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @shasums.each do |shasum| %>
      <tr>
        <td><%= shasum.sum %></td>
        <td></td>
        <td><%= shasum.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shasums/new.html.erb
<h1>New shasum</h1>

<%= render 'form' %>

<%= link_to 'Back', shasums_path %>

app/views/shasums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sum:</strong>
  <%= @shasum.sum %>
</p>

<%= link_to 'Edit', edit_shasum_path(@shasum) %> |
<%= link_to 'Back', shasums_path %>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.username %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @ticket.username %>
</p>

<%= link_to 'Back', tickets_path %>

app/views/winners/_form.html.erb
<%= form_for(@winner) do |f| %>
  <% if @winner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@winner.errors.count, "error") %> prohibited this winner from being saved:</h2>

      <ul>
      <% @winner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/winners/edit.html.erb
<h1>Editing winner</h1>

<%= render 'form' %>

<%= link_to 'Show', @winner %> |
<%= link_to 'Back', winners_path %>

app/views/winners/index.html.erb
<h1>Listing winners</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @winners.each do |winner| %>
      <tr>
        <td><%= winner.username %></td>
        <td><%= link_to 'Show', winner %></td>
        <td><%= link_to 'Edit', edit_winner_path(winner) %></td>
        <td><%= link_to 'Destroy', winner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Winner', new_winner_path %>

app/views/winners/new.html.erb
<h1>New winner</h1>

<%= render 'form' %>

<%= link_to 'Back', winners_path %>

app/views/winners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @winner.username %>
</p>

<%= link_to 'Edit', edit_winner_path(@winner) %> |
<%= link_to 'Back', winners_path %>